            - имя: Загрузить артефакт сборки
  используется: actions/download-artifact@v7.0.0
  с:
    # Название загружаемого артефакта. Если не указано, загружаются все артефакты для данного запуска.
    имя: # необязательно
    # Идентификаторы артефактов для загрузки, разделенные запятыми. Можно использовать либо `artifact-ids`, либо `name`, но не оба одновременно.
    artifact-ids: # необязательно
    # Путь назначения. Поддерживается базовое расширение тильды. По умолчанию используется $GITHUB_WORKSPACE
    путь: # необязательно
    # Шаблон glob, соответствующий артефактам, которые следует загрузить. Игнорируется, если указано имя.
    шаблон: # необязательный
    # Если найдено несколько совпадений, это изменяет поведение целевых каталогов. Если true, загруженные артефакты будут находиться в том же каталоге, что и указанный путь. Если false, загруженные артефакты будут извлечены в отдельные именованные каталоги внутри указанного пути.
    merge-multiple: # необязательный параметр, по умолчанию false
    # Токен GitHub, используемый для аутентификации в API GitHub. Он необходим при загрузке артефактов из другого репозитория или из другого запуска рабочего процесса. Если он не указан, действие попытается загрузить артефакты из текущего репозитория и текущего запуска рабочего процесса.
    github-token: # необязательный
    # Владелец репозитория и имя репозитория, объединенные символом "/". Если указан github-token, это репозиторий, из которого будут загружаться артефакты.
    репозиторий: # необязательно, по умолчанию ${{ github.repository }}
    # Идентификатор запуска рабочего процесса, из которого был загружен желаемый артефакт для скачивания. Если указан github-token, то именно из этого запуска будут загружены артефакты.
    run-id: # необязательный параметр, по умолчанию ${{ github.run_id }}
           
